language: python

before_script:
  - psql -c "CREATE DATABASE prueba;" -U postgres
  - psql -c "CREATE USER samantha_guzman WITH PASSWORD 'pass';" -U postgres
services:
    - postgresql
install:
    - pip install django djangorestframework djangorestframework-simplejwt PyJWT django-cors-headers psycopg2
script:
    - python manage.py test
