# Generated by Django 3.2.9 on 2021-11-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersproducts',
            old_name='orders',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
